### ISSUE TITLE
dev.user branch problem

### ISSUE THREAD

**Issue by vagabondan** [vagabondan/CoiniumServ#14]

**Comment by vagabondan** [comment]
@vkynchev I'll investigate issues with my stand a bit later. I've recreated only MySQL DB. Redis, and configs stayed the same.
First issue is reproduced on develop branch too after DB recreation. The second one is something new.

**Comment by vkynchev** [comment]
@vagabondan The second one is probably even not an issue... Just there is no record with that username in the DB
<img width="592" alt="screen shot 2017-08-20 at 22 59 27" src="https://user-images.githubusercontent.com/10143016/29497975-445edff4-85fb-11e7-89ca-fe162f68d31d.png">

**Comment by vkynchev** [comment]
@vagabondan Also many of the changes in `034da4c` are just like this one... Logging errors when there is no need to do so (which should be replaced by Debug or removed).

**Comment by vagabondan** [comment]
@vkynchev Yes, these messages should be changed on Debug, but return null instead of correct format object is wrong for me and should be fixed too (at least for the first issue).
Second one handles nulls correctly.
Fix is here: https://github.com/vagabondan/CoiniumServ/commit/aac98c2767a01cbb344b5460e1a2edef2cbaa48f

I had filled catches with errors/debug messages earlier just to study this app closely: there were many catches with emty brackets at all. It's bad because you may never know about some problems. 
Their investigation is rather complicated. So I consider this just as code audit procedure that we should survive.

**Comment by vagabondan** [comment]
Now everything is fine. Merged changes to develop branch. Deleted dev.users. Thank you!
