### ISSUE TITLE
Which Redis to use as the server

### ISSUE THREAD

**Issue by Mer-idium** [vagabondan/CoiniumServ#2]
@vagabondan I ams till confused in what Redis client to use as the local server. Should we use StackExchange Redis because that is what is configured in the fork? Or does it not matter what version we use as the local server, only what package is utalised in the build?

**Comment by Mer-idium** [comment]
@vagabondan  Also i did see your push 12 days ago "Market&Profitability view is now working again", however i am still receiving the error "coiniumserv.markets.marketManager [Global] Sequence contains no elements". Do we need to configure a new markets file or add/remove a market object?

Thanks

**Comment by vagabondan** [comment]
@pfeiflelukas StackExchange.Redis client should be used. Redis server as I remember should be greater than 2.5. I'm using redis-server 3.0.6 and it's running well.

**Comment by vagabondan** [comment]
@pfeiflelukas I just changed USD to USDT in ProfitInfo.cs and Market data became working with Poloniex as I remember. We do not need to configure new markets.
![image](https://user-images.githubusercontent.com/2213110/29054372-82999d88-7bfe-11e7-9fa5-bb0482dae1c6.png)
