### ISSUE TITLE
Issues mining Dashcoin with X11 algorithm - No masternode support

### ISSUE THREAD

**Issue by DecentralizeCoding** [vagabondan/CoiniumServ#26]
Hi there,

I am currently having issues mining dashcoin with the X11 algo. It keeps coming back with with negative number and causes mining submit to fail.

I have looked around and it seems it is to do with no masternode support and found some links to other pools that have tried to implement it and got it working well.

@vagabondan I noticed in another issue thread that you were talking with another devloper over skype and found this issue referenced here: https://github.com/vagabondan/CoiniumServ/issues/17 I know you are not working on this anymore but I thought it is worth a shot asking if you found a soluton?

PS - I have tried to implement ric-nomp a few times but keep getting dependency errors on linux and windows, if you have a compiled and downloaded copy you could send over to me that would be much appreicated!

Many Thanks!

Kind Regards,

James

**Comment by vagabondan** [comment]
Hi, did you 
`git clone https://github.com/vagabondan/ric-nomp`
?
It works perfectly with node.js 6.X.X

**Comment by DecentralizeCoding** [comment]
Good Evening @vagabondan 

Yes I have got that working since getting node on version 6.

Thanks for your help!

Kind Regards,

James
