### ISSUE TITLE
Clarify is status is still correct

### ISSUE THREAD

**Issue by Kukks** [vagabondan/CoiniumServ#29]
`NOTE: No plans to return to this project because I've switched to more convenient and stable NOMP pool (https://github.com/vagabondan/ric-nomp) and recommend you to do the same.`

Is this still accurate? Seems like there is more work being done here than the ric-nomp repo. :)

**Comment by vagabondan** [comment]
@Kukks Status is actual. It was just 20 minutes to merge pull request here. 
NOMP is highly modular. The truth is in the depths of it;)
