### ISSUE TITLE
Possible solution for redis connection issues...

### ISSUE THREAD

**Issue by vkynchev** [vagabondan/CoiniumServ#6]
Possible fix for people having connection problems with redis is to change Providers/Redis/RedisProvider.cs:62
from `Client = new RedisClient(_config.Host, _config.Port, _config.Password, "version=2.6");`
to `Client = new RedisClient(_config.Host, _config.Port, _config.Password, "version=2.6,abortConnect=false,ssl=false");`

**Comment by vagabondan** [comment]
Hi!
What kind of redis connection issues do you expect to resolve by such changes?

**Comment by vkynchev** [comment]
I am hosting everything in docker containers and they are linked between each other with virtual network. Their IPs are dynamic, so the only way to access them is by hostname (which is set in `docker-compose.yaml`)...
The issue happens when I try to connect to redis' hostname(`redis:6379`), but if I setup port-forwarding to the main host and connect to the host IP (`192.168.1.xxx:6379`) it is connecting... 
This is the error: `It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail.` Nothing else, no timeout or so...

BTW: I'm using latest redis image which is 4.0

**Comment by vagabondan** [comment]
Ok, thank you. I'll try it on my stand and commit then.

**Comment by vagabondan** [comment]
According to https://github.com/vagabondan/CoiniumServ/issues/4#issuecomment-322146455 the reason was bug in StackExchange v1.2.5-1.2.6.
The changes proposed do not really help to resolve the issue:  they expect to get connection on multiplexer object instantiation.
