### ISSUE TITLE
Implement SEGWIT: BIP-145

### ISSUE THREAD

**Issue by vagabondan** [vagabondan/CoiniumServ#8]
Comming soon...

**Comment by vkynchev** [comment]
[This](https://github.com/UNOMP/node-merged-pool/pull/4/files) could help... I think... 🙂

**Comment by vagabondan** [comment]
I've done it actually, just testing rewards mechanism...

**Comment by vkynchev** [comment]
oh... nice 🙂

**Comment by vagabondan** [comment]
https://github.com/vagabondan/CoiniumServ/commit/87b43bb2786e1f8a03579999a2ad166237b35a75

**Comment by vkynchev** [comment]
@vagabondan How can I test if SEGWIT works? On which testnet did you tested it?

**Comment by vagabondan** [comment]
@vkynchev  testnet4 for instance.

**Comment by vkynchev** [comment]
@vagabondan Are you talking about LTC's testnet4, because I've been mining blocks there before the integration?

**Comment by vagabondan** [comment]
@vkynchev Yes, sorry, LTC testnet4.

**Comment by vagabondan** [comment]
![image](https://user-images.githubusercontent.com/2213110/29451676-3a9aeca6-840c-11e7-982d-fc22558f78be.png)
![image](https://user-images.githubusercontent.com/2213110/29451725-619631f8-840c-11e7-858f-2bcef932fc9b.png)

**Comment by vkynchev** [comment]
This is from before the implementation...
Yours block: [link](http://explorer.litecointools.com/block/656955aba6e0516130ab5290b8d1592be15211117d1db744d18e7f8ba74f0057)
Mine block: [link](http://explorer.litecointools.com/block/53483d96b007a95c7e8ad7311c05e860d6daa9da8619dcbfb8a5e1e0ff742bf9)
<img width="1280" alt="screen shot 2017-08-18 at 11 59 09" src="https://user-images.githubusercontent.com/10143016/29451901-074a0ad4-840d-11e7-8133-aaf37dd35a96.png">
<img width="1280" alt="screen shot 2017-08-18 at 11 59 42" src="https://user-images.githubusercontent.com/10143016/29451902-0766230e-840d-11e7-9cd7-e55f46dd6fc3.png">

**Comment by vkynchev** [comment]
@vagabondan After a week or two I'm gonna test CoiniumServ with ~60GH/s on LTC mainnet... I'll post here blocks found by the pool if you want...

**Comment by vagabondan** [comment]
@vkynchev It would be great!
I haven't got blocks on LTC mainnet yet, but got one orphaned block after these changes implementation. 
Before them I got: 
AcceptBlock FAILED: bad-txnmrklroot, hashMerkleRoot mismatch (code 16)

**Comment by vagabondan** [comment]
I got confirmation from LTC mainnet: works fine.
